config/routes.rb
SampleApp::Application.routes.draw do
  resources :questions

  get "quiz/index"
  
  post "quiz/start"

  get "quiz/question"
  
  post "quiz/question"

  post "quiz/answer"

  get "quiz/end"
  
  post "choices/create"
  
  post "choices/destroy"


  resources :choices


  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'











end

app/models/question.rb
class Question < ActiveRecord::Base
attr_accessible :text
  has_many :choices
  
  def answer
	 uncorrect
	 choices.select {|c| c.correct}[0]
  end	
  
  def uncorrect
	 choices.each {|c| c.correct = false}
  end
  
  def answer= choice
	 if !answer.nil?
		answer.correct = false
	 end
	 
	 if choices.include? choice
		choice.correct = true
	 else
		choices << choice
		choice.correct = true
	 end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
 #before_filter :signed_in_user
  # GET /questions
  # GET /questions.xml
  def index
    @questions = Question.all
    @questions.sort! {|a,b| a.text <=> b.text}

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question, :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end
  def signed_in_user
    redirect_to sign_in_path, notice: "Please sign in."     unless signed_in?
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text, :size => "50x3" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  Edit Question
<% end %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<p>Total: <%= @questions.size %></p>
<p><%= link_to 'New Question', new_question_path %></p>

<table border="1">
  <tr>
    <th>Text</th>
    <th>Choices</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.text %></td>
    <td>
      <ul>
        <% question.choices.each do |choice| %>
          <li>
            <%= choice.text %>
            <% if choice.correct %> (Correct) <% end %>
          </li>
        <% end %>
      </ul>
    </td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>



<% content_for(:title) do %>
  All Questions
<% end %>

app/views/questions/new.html.erb
<h1>Create New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

<% content_for(:title) do %>
  New Question
<% end %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @question.text %>
</p>

<h4>Choices</h4>
<ul>
  <% @question.choices.each do |choice| %>
	 <li>
		<%= choice.text %>
		<% if choice.correct %> (Correct) <% end %>
		
		<%= form_tag({:controller => "choices", :action => "destroy"}) do %>
		  <%= hidden_field_tag :question, @question.id %>
		  <%= hidden_field_tag :choice, choice.id %>
		  <%= submit_tag "Delete" %>
		<% end %>
		
	 </li>
  <% end %>
</ul>

<h5>New Choice</h5>
<%= form_tag({:controller => "choices", :action => "create"}) do %>
  <%= hidden_field_tag :question, @question.id %>
  
  <%= label_tag :text, "Text" %><br />
  <%= text_field_tag :text %>
  <br />
  <%= check_box_tag :correct %>
  <%= label_tag :correct, "Correct" %>
  <br />
  <%= submit_tag "Create" %>
<% end %>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %> | <%= link_to 'New Question', new_question_path %>

<% content_for(:title) do %>
  Question Details
<% end %>