config/routes.rb
SampleApp::Application.routes.draw do
  resources :questions

  get "quiz/index"
  
  post "quiz/start"

  get "quiz/question"
  
  post "quiz/question"

  post "quiz/answer"

  get "quiz/end"
  
  post "choices/create"
  
  post "choices/destroy"


  resources :choices


  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'











end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  	
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
	BetaGram app is an online application which teaches people how to perfect the English Language grammar. It is very good for prospective students of GRE, TOEFL and all other examinations where grammar is tested. It is expected that users would be able to test their ability to communicate in the English Language after going through our quiz. Thanks!
</p>


app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
	<h1>Contact</h1>
	<p>
		You can send a mail to us on abimbola2010@yahoo.com or danijuysuf@yahoo.co.uk
	</p>


app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
	<h1>Help</h1>
	<p>
		All you need to do is to choose the category of quiz you want to answer and start to feel the experience of being in the hot seat. In case you have not signed up, click here.

	</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to BetaGram App</h1>
	<h2>
		This is the home page for the BetaGram App that helps you 'Mind Your Grammar!'
	</h2>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
	<%= link_to "Sign in!", signin_path, class: "btn btn-large btn-primary" %>
</div>