config/routes.rb
SampleApp::Application.routes.draw do
  resources :questions

  get "quiz/index"
  
  post "quiz/start"

  get "quiz/question"
  
  post "quiz/question"

  post "quiz/answer"

  get "quiz/end"
  
  post "choices/create"
  
  post "choices/destroy"


  resources :choices


  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

  
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/contact', to: 'static_pages#contact'











end

app/models/choice.rb
class Choice < ActiveRecord::Base
  attr_accessible :text, :correct, :question_id
  belongs_to :question
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  
  def create
   @question = Question.find(params[:question])
   text = params[:text]
   correct = params[:correct] == "1"
   new = Choice.create(:text => text, :correct => correct, :question_id => @question.id)
   
   if new.correct
    @question.answer = new
   end
   
   redirect_to question_path(@question)
  end
  
  def destroy
   @question = Question.find(params[:question])
   @choice = Choice.find(params[:choice])
   @choice.destroy
   redirect_to question_path(@question)
  end
  
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_form.html.erb
<%= form_for(@choice) do |f| %>
  <% if @choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% @choice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing choice</h1>

<%= render 'form' %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<h1>Listing choices</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @choices.each do |choice| %>
  <tr>
    <td><%= link_to 'Show', choice %></td>
    <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
    <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1>New choice</h1>

<%= render 'form' %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>